### ISSUE TITLE
Add demo3D51

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/docker-cellorganizer-jupyter-notebook#16]
@RuijiaChen check the latest version of the demo on 

* http://repositories.compbio.cs.cmu.edu/cellorganizer/cellorganizer3

and update Jupyter notebook.

**Comment by RuijiaChen** [comment]
You mean create a Jupiter notebook of demo3D51?
@icaoberg

**Comment by icaoberg** [comment]
@RuijiaChen  correct. Make MR and remember to close the ticket after I approve the MR.
