### ISSUE TITLE
Add 3D demos 

### ISSUE THREAD

**Issue by asankar** [murphygroup/docker-cellorganizer-jupyter-notebook#29]
Add all 3D demos to Docker

**Comment by asankar** [comment]
@wvelebanks I am finishing the 2D demos. Please add all 3D demos from 0-20 that have not been added yet, and also are not deprecated.

**Comment by asankar** [comment]
**Also if the demo makes a call to a func. that is not img2slml, slml2img, slml2info, slml2report, or slml2report there is no need to add it.

**Comment by wvelebanks** [comment]
done already.
