### ISSUE TITLE
Remove model

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/docker-cellorganizer-jupyter-notebook#34]
Remove large model

<img width="1158" alt="Screenshot 2019-04-01 11 17 29" src="https://user-images.githubusercontent.com/413752/55339172-2b3d0380-5470-11e9-9258-8898ebd19905.png">

**Comment by asankar** [comment]
@icaoberg Ok that can be removed on the install. BUt do you still want only the 3D diffeo models installed initially. Let me know which ones you want instead

**Comment by asankar** [comment]
Models set are 2D hela_pca and 3d diffeo
