### ISSUE TITLE
Check model size

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/docker-cellorganizer-jupyter-notebook#35]
Pretty sure the size is wrong. Maybe it is corrupted?

<img width="1157" alt="Screenshot 2019-04-01 11 23 19" src="https://user-images.githubusercontent.com/413752/55339410-9a1a5c80-5470-11e9-859a-fd771ccf4c74.png">

**Comment by asankar** [comment]
![image](https://user-images.githubusercontent.com/10892980/55341208-3bef7880-5474-11e9-8d28-4b48aef81ef7.png)
@icaoberg It's consistent with what is on the cellorganizer webpage
