### ISSUE TITLE
Add 2D PCA models

### ISSUE THREAD

**Issue by icaoberg** [murphygroup/docker-cellorganizer-jupyter-notebook#36]
There are no 2D models on repo

<img width="1176" alt="Screenshot 2019-04-01 11 31 58" src="https://user-images.githubusercontent.com/413752/55340014-d00c1080-5471-11e9-93cb-5d0f9e47d3d8.png">

**Comment by asankar** [comment]
@icaoberg It's on master

**Comment by asankar** [comment]
Added now
