### ISSUE TITLE
Demo3D05 not running

### ISSUE THREAD

**Issue by jhinojos** [murphygroup/docker-cellorganizer-jupyter-notebook#5]
Error when running demo3d05
Probably running out of memory.

![image pasted at 2018-7-27 14-17](https://user-images.githubusercontent.com/41013551/43339642-e814680e-91a7-11e8-981d-05c40b39fd64.png)

**Comment by icaoberg** [comment]
@RuijiaChen demo is running out of memory. Remove from repository.

**Comment by icaoberg** [comment]
@RuijiaChen remove both script and Jupyter notebook.

**Comment by RuijiaChen** [comment]
@icaoberg jupyter notebook of demo3D05 was already removed, what does script means?

**Comment by icaoberg** [comment]
Too old.
