### ISSUE TITLE
The docker container cannot be created correctly

### ISSUE THREAD

**Issue by RuijiaChen** [murphygroup/docker-cellorganizer-jupyter-notebook#6]
<img width="1248" alt="screen shot 2018-08-05 at 6 54 31 pm" src="https://user-images.githubusercontent.com/37483817/43690929-08a16852-98e1-11e8-9998-98485423d87b.png">
<img width="1207" alt="screen shot 2018-08-05 at 6 54 39 pm" src="https://user-images.githubusercontent.com/37483817/43690930-0c6262d4-98e1-11e8-9a8a-20b2fc9cd7a8.png">
the models are incomplete

**Comment by icaoberg** [comment]
Formula has been updated and models are present.
